dist: bionic

language: rust
rust:
  - nightly

os:
  - linux
#  - osx

sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf autogen libtool texinfo mpich libmpich-dev
