[package]
name = "neworder"
version = "0.1.0"
authors = ["virgesmith <andrew@friarswood.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "*"
numpy = "*"
ndarray = "*"
mpi = "*"
lazy_static = "*"
num = "*"
argparse = "*"
rand = "0.4.6"
mersenne_twister = "*"
